#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

tee /etc/yum.repos.d/CentOS-rt.repo >/dev/null <<EOF
[rt]
name=CentOS-7 - rt
baseurl=http://mirror.centos.org/centos/\$releasever/rt/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
EOF

yum -y remove tuned

yum install -y kernel-rt rt-tests tuned-profiles-realtime tuned-profiles-nfv-guest
