#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ ${DISTRO_NAME} =~ "centos" ]]; then
    yum install -y \
        centos-release-openstack-train \
        centos-release-ansible-29 \
        centos-release-qemu-ev
    yum install -y \
        ansible
    yum install -y \
        mariadb
    yum -y install \
        atop \
        bcc \
        bcc-tools \
        blktrace \
        dstat \
        ethtool \
        htop \
        iotop \
        iproute \
        lldpad \
        lsof \
        ltrace \
        numactl \
        openvswitch \
        perf \
        procps-ng \
        strace \
        sysstat \
        tcpdump \
        tiptop \
        tmux
    # performance benchmark tools
    yum -y install \
        httpd-tools \
        fio \
        hping3 \
        sysbench \
        traceroute \
        mtr \
        hdparm \
        smartmontools
    # Performance tunning tools
    yum -y install \
        systemtap-client \
        kpatch

elif [[ ${DISTRO_NAME} =~ "ubuntu" ]]; then
    apt-get install -y \
        lsof \
        net-tools \
        strace \
        sysstat \
        tcpdump \
        watchdog
fi
