#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ ${DISTRO_NAME} =~ "centos" ]]; then
    yum install -y \
        lsof \
        net-tools \
        perf \
        strace \
        sysstat \
        tcpdump \
        watchdog
elif [[ ${DISTRO_NAME} =~ "ubuntu" ]]; then
    apt-get install -y \
        lsof \
        net-tools \
        strace \
        sysstat \
        tcpdump \
        watchdog

fi
