---
name: build images

on:
  - push

jobs:
  build_ironic_centos7:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run ansible deployment playbooks
        run: |
          sudo -E bash -x tests/start.sh build_ironic_centos7
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

  build_centos7:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run ansible deployment playbooks
        run: |
          sudo -E bash -x tests/start.sh build_centos7
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

  build_centos7-dev:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run ansible deployment playbooks
        run: |
          sudo -E bash -x tests/start.sh build_centos7-dev
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

  build_ubuntu_bionic:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run ansible deployment playbooks
        run: |
          sudo -E bash -x tests/start.sh build_ubuntu_bionic
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
